class Boss extends Moveable{
	constructor(x,y){
		super(x,y);
		this.hit=false;
		this.width=120;
		this.height=100;
		this.health=2000;
		this.hitCounter=3;
		this.color="#FFFFFF";
		this.sound=undefined;
		this.RIFLE_GUN_WARM=40;
		this.SNIPER_GUN_WARM=546;
		this.TURRENT_GUN_WARM=200;
		this.total_turrent_ammo=6;
		this.sniper_sound=undefined;
		this.turrent_ammo=this.total_turrent_ammo;	
		this.sniper_warm_counter=this.SNIPER_GUN_WARM;
		this.rifle_warm_counter=this.RIFLE_GUN_WARM;
		this.turrent_warm_counter=this.TURRENT_GUN_WARM;
	}

	shootBullet(){
		if(this.turrent_warm_counter==0){
			game.world.triggerBullet(this.x+this.width/2,this.y+this.height+2,false,true);
			this.turrent_ammo--;
			if(this.turrent_ammo==0){
				this.turrent_warm_counter=this.TURRENT_GUN_WARM;		
				this.turrent_ammo=this.total_turrent_ammo;
			}else{
				this.turrent_warm_counter=5;	
				this.sound=sound.get("turrent").cloneNode();
				this.sound.volume=0.4;
				this.sound.play();
			}
		}
		if(this.rifle_warm_counter==0){
			if((player.x+player.width)>this.x && (this.x+this.width)>player.x){
				game.world.triggerBullet(this.x+this.width/4,this.y+this.height+2,false,false,true);
				game.world.triggerBullet(this.x+this.width/4+this.width/2,this.y+this.height+2,false,false,true);
				this.sound=sound.get("player").cloneNode();
				this.sound.volume=0.05;
				this.sound.play();
				this.rifle_warm_counter=this.RIFLE_GUN_WARM;
			}
		}
		if(this.sniper_warm_counter<50){
			this.color="#969696";
		}
		if(this.sniper_warm_counter==0){
			game.world.triggerBullet(this.x+this.width/2,this.y+this.height+2,false,true,false,true);
			this.sniper_sound=sound.get("sniper").cloneNode();
			this.sniper_sound.play();
			this.color="#ffffff";
			this.sniper_warm_counter=this.SNIPER_GUN_WARM;
		}
	}

	TickWarm(){
		if(this.turrent_warm_counter>0){
			this.turrent_warm_counter--;
		}
		if(this.rifle_warm_counter>0){
			this.rifle_warm_counter--;
		}
		if(this.sniper_warm_counter>0){
			this.sniper_warm_counter--;
		}
		if(this.hit){
			if(this.hitCounter>0){
				this.hitCounter--;
			}
			if(this.hitCounter==0){
				this.hit=false;
				this.color='#ffffff'	
			}
		}
	}
	bulletDamage(){
		this.health-=10;
		this.hit=true;
		this.hitCounter=3;
		this.color="#ff4646";
	}
}