
class Enemy{
	constructor(x,y){
		this.health=100;
		this.x=x;
		this.y=y;
		this.x_velocity=4;
		this.y_velocity=4;
		this.height=40;
		this.width=30;
		this.color="#DDEE11";
		this.warm_counter=0;
		this.GUN_WARM=10;	
		this.hit=false;
		this.hitCounter=3;
	}
	
	shootBullet(){
		if(this.warm_counter==0){
			game.world.triggerBullet(this.x+this.width/2,this.y+this.height+2,false,false);
			this.warm_counter=this.GUN_WARM;	
		}
	}

	TickWarm(){
		if(this.warm_counter>0){
			this.warm_counter--;
		}
		if(this.hit){
			if(this.hitCounter>0){
				this.hitCounter--;
			}
			if(this.hitCounter==0){
				this.hit=false;
				this.color="#DDEE11";
			}
		}
	}
	bulletDamage(){
		this.health-=10;
		this.hit=true;
		this.hitCounter=3;
		this.color="#ff4646";
	}
	moveLeft(){
		this.x+=-this.x_velocity;
	}
	moveRight(){
		this.x+=this.x_velocity;
	}
	moveUp(){
		this.y+=-this.y_velocity;
	}
	moveDown(){
		this.y+=this.y_velocity;
	}
}